# -*- coding: utf-8 -*-
"""tiger_helpers

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1lyqs280zSaO_8WdkEgWKyGE6t32XORD9
"""

# === Imports (only what you used) ===
import warnings, zipfile, numpy as np, pandas as pd, matplotlib.pyplot as plt
import statsmodels, statsmodels.api as sm
import plotly.express as px, plotly.graph_objects as go
from scipy.interpolate import CubicSpline
from scipy.optimize import curve_fit
from linearmodels.panel import PanelOLS
import plotly.io as pio
pio.renderers.default = "colab"

# ---------- Data load ----------
def load_data():
    url = "https://raw.githubusercontent.com/Mergim1110/Tiger_MGMT_499/refs/heads/main/final_panel_with_green_indicator.csv"
    df = pd.read_csv(url, sep=",")
    return df

# ---------- Model 1 (Simple OLS) ----------
def model1_simple_ols(df):
    X = df[['heatwave_30_3d']]
    X = sm.add_constant(X)
    y = df['crime_rate']
    model = sm.OLS(y, X)
    return model.fit()

# ---------- Maps (LAPD shapefile) ----------
def make_maps(df, shapefile_zip_path):
    import geopandas as gpd
    with zipfile.ZipFile(shapefile_zip_path, 'r') as zip_ref:
        zip_ref.extractall('/tmp/lapd_shapefile')
    districts_gdf = gpd.read_file('/tmp/lapd_shapefile')

    district_summary = df.groupby('district_id').agg({
        'heatwave_30_3d': 'mean',
        'crime_rate': 'mean'
    }).reset_index()

    districts_gdf['district_id'] = districts_gdf['PREC'].astype(int)
    districts_gdf = districts_gdf.merge(district_summary, on='district_id', how='left')

    print("\nMerged successfully!")
    print(districts_gdf[['district_id', 'APREC', 'heatwave_30_3d', 'crime_rate']].head())

    fig, axes = plt.subplots(1, 2, figsize=(16, 8))
    districts_gdf.plot(column='heatwave_30_3d', ax=axes[0], cmap='YlOrRd',
                       legend=True, edgecolor='black', linewidth=0.5,
                       legend_kwds={'label': 'Heatwave Frequency', 'shrink': 0.8})
    axes[0].set_title('Heatwave Exposure by LAPD District (2020-2023)', fontsize=14, fontweight='bold')
    axes[0].axis('off')

    districts_gdf.plot(column='crime_rate', ax=axes[1], cmap='Reds',
                       legend=True, edgecolor='black', linewidth=0.5,
                       legend_kwds={'label': 'Domestic Violence Rate', 'shrink': 0.8})
    axes[1].set_title('Domestic Violence Rate by LAPD District (2020-2023)', fontsize=14, fontweight='bold')
    axes[1].axis('off')

    plt.tight_layout()
    plt.savefig('la_districts_maps.png', dpi=300, bbox_inches='tight')
    plt.show()
    print("\nMap saved as 'la_districts_maps.png'")

# ---------- Model 2 (Panel FE + controls) ----------
def model2_panel_fe(df):
    df = df.copy()
    df['date'] = pd.to_datetime(df['date'])
    panel = df.set_index(["district_id", "date"])
    y = panel["crime_rate"]
    X = panel[["heatwave_30_3d", "precip", "humidity_mean", "holiday"]].copy()
    X = X.join(pd.get_dummies(panel["dow"], prefix="dow", drop_first=True))
    X = X.join(pd.get_dummies(panel["month"], prefix="m", drop_first=True))
    X = X.join(pd.get_dummies(panel["year"], prefix="y", drop_first=True))
    mod = PanelOLS(y, X, entity_effects=True)
    return mod.fit(cov_type="clustered", cluster_entity=True)

# ---------- Model 3 (Panel FE + greenness interaction) ----------
def model3_panel_green(df):
    df = df.copy()
    df['date'] = pd.to_datetime(df['date'])
    df['heatwave_green'] = df['heatwave_30_3d'] * df['green']
    panel = df.set_index(["district_id", "date"])
    y = panel["crime_rate"]
    X = panel[["heatwave_30_3d", "heatwave_green", "precip", "humidity_mean", "holiday"]].copy()
    X = X.join(pd.get_dummies(panel["dow"], prefix="dow", drop_first=True))
    X = X.join(pd.get_dummies(panel["month"], prefix="m", drop_first=True))
    X = X.join(pd.get_dummies(panel["year"], prefix="y", drop_first=True))
    mod = PanelOLS(y, X, entity_effects=True)
    return mod.fit(cov_type="clustered", cluster_entity=True)

# ---------- Greenness β + CI visual (your logic) ----------
def _get_cov_df_from_res(result):
    import pandas as pd, numpy as np
    candidates = []
    for name in ['cov', 'cov_params', 'covariance', '_cov']:
        if hasattr(result, name):
            obj = getattr(result, name)
            mat = obj() if callable(obj) else obj
            if mat is not None:
                candidates.append(mat)
    for mat in candidates:
        if hasattr(mat, 'loc') and hasattr(mat, 'columns'):
            try:
                _ = mat.loc[result.params.index, result.params.index]
                return mat
            except Exception:
                pass
        try:
            arr = np.asarray(mat)
            if arr.ndim == 2 and arr.shape[0] == arr.shape[1] == len(result.params):
                return pd.DataFrame(arr, index=result.params.index, columns=result.params.index)
        except Exception:
            pass
    se = np.asarray(result.std_errors)
    diag = np.diag(se**2)
    return pd.DataFrame(diag, index=result.params.index, columns=result.params.index)

def plot_greenness_ci(res, save_path='betas_ci_greenness_clean.png'):
    import matplotlib.patches as patches, numpy as np
    b1  = float(res.params['heatwave_30_3d'])
    bi  = float(res.params['heatwave_green'])
    se1 = float(res.std_errors['heatwave_30_3d'])
    sei = float(res.std_errors['heatwave_green'])
    cov_df = _get_cov_df_from_res(res)
    cov_b1_bi = float(cov_df.loc['heatwave_30_3d', 'heatwave_green'])
    beta_ng = b1; lo_ng = b1 - 1.96*se1; hi_ng = b1 + 1.96*se1
    beta_g  = b1 + bi
    se_g = float(np.sqrt(max(se1**2 + sei**2 + 2*cov_b1_bi, 0)))
    lo_g = beta_g - 1.96*se_g; hi_g = beta_g + 1.96*se_g

    labels = ['OLS: Non-green', 'OLS: Green']; xpos=[0,1]; width=.6; ci_cols=['#ADD8E6','#F4A6A6']
    fig, ax = plt.subplots(figsize=(10,6))
    for x,(b,lo,hi),col in zip(xpos, [(beta_ng,lo_ng,hi_ng),(beta_g,lo_g,hi_g)], ci_cols):
        from matplotlib.patches import Rectangle
        ax.add_patch(Rectangle((x-width/2, lo), width, hi-lo, linewidth=0, facecolor=col, alpha=0.5))
        ax.plot([x-width/2, x+width/2], [b,b], color='black', linewidth=4)
    ax.set_xticks(xpos); ax.set_xticklabels(labels)
    ax.set_ylabel('Effect of heatwave on domestic violence (β)')
    ax.set_title('Coefficients and 95% Confidence Intervals\n(PanelOLS with entity and time FE, SE clustered)')
    ax.yaxis.grid(True, linestyle='--', alpha=0.35); ax.set_axisbelow(True)
    plt.tight_layout(); plt.savefig(save_path, dpi=300, bbox_inches='tight'); plt.show()

# ---------- Appendix OLS table (your print layout) ----------
def ols_table(df):
    import pandas as pd
    df = df.copy(); df['date'] = pd.to_datetime(df['date'])

    X1 = sm.add_constant(df[['heatwave_30_3d']]); y1 = df['crime_rate']
    res1 = sm.OLS(y1, X1).fit()

    panel = df.set_index(["district_id", "date"])
    y2 = panel["crime_rate"]
    X2 = panel[["heatwave_30_3d", "precip", "humidity_mean", "holiday"]].copy()
    X2 = X2.join(pd.get_dummies(panel["dow"], prefix="dow", drop_first=True))
    X2 = X2.join(pd.get_dummies(panel["month"], prefix="m", drop_first=True))
    X2 = X2.join(pd.get_dummies(panel["year"], prefix="y", drop_first=True))
    res2 = PanelOLS(y2, X2, entity_effects=True).fit(cov_type="clustered", cluster_entity=True)

    df['heatwave_green'] = df['heatwave_30_3d'] * df['green']
    panel = df.set_index(["district_id", "date"])
    y3 = panel["crime_rate"]
    X3 = panel[["heatwave_30_3d", "heatwave_green", "precip", "humidity_mean", "holiday"]].copy()
    X3 = X3.join(pd.get_dummies(panel["dow"], prefix="dow", drop_first=True))
    X3 = X3.join(pd.get_dummies(panel["month"], prefix="m", drop_first=True))
    X3 = X3.join(pd.get_dummies(panel["year"], prefix="y", drop_first=True))
    res3 = PanelOLS(y3, X3, entity_effects=True).fit(cov_type="clustered", cluster_entity=True)

    def get_stars(p):
        if p < 0.001: return '***'
        if p < 0.01: return '**'
        if p < 0.05: return '*'
        return ''

    print("\n" + "="*80)
    print("Dependent Variable: Domestic Violence Rate")
    print("="*80)
    print(f"{'Variable':<25} {'(1)':<20} {'(2)':<20} {'(3)':<20}")
    print(f"{'':25} {'Simple OLS':<20} {'FE + Controls':<20} {'With Greenness':<20}")
    print("-"*80)
    print(f"{'Intercept':<25} {res1.params['const']:.4f}{get_stars(res1.pvalues['const']):<16} {'—':<20} {'—':<20}")
    print(f"{'':25} ({res1.bse['const']:.4f}){'':<11}")
    print(f"{'Heatwave (30°C, 3d)':<25} "
          f"{res1.params['heatwave_30_3d']:.4f}{get_stars(res1.pvalues['heatwave_30_3d']):<16} "
          f"{res2.params['heatwave_30_3d']:.4f}{get_stars(res2.pvalues['heatwave_30_3d']):<16} "
          f"{res3.params['heatwave_30_3d']:.4f}{get_stars(res3.pvalues['heatwave_30_3d']):<16}")
    print(f"{'':25} ({res1.bse['heatwave_30_3d']:.4f}){'':<11} ({res2.std_errors['heatwave_30_3d']:.4f}){'':<11} ({res3.std_errors['heatwave_30_3d']:.4f})")
    print(f"{'Precipitation':<25} {'—':<20} "
          f"{res2.params['precip']:.4f}{get_stars(res2.pvalues['precip']):<16} "
          f"{res3.params['precip']:.4f}{get_stars(res3.pvalues['precip']):<16}")
    print(f"{'':25} {'':20} ({res2.std_errors['precip']:.4f}){'':<11} ({res3.std_errors['precip']:.4f})")
    print(f"{'Humidity':<25} {'—':<20} "
          f"{res2.params['humidity_mean']:.4f}{get_stars(res2.pvalues['humidity_mean']):<16} "
          f"{res3.params['humidity_mean']:.4f}{get_stars(res3.pvalues['humidity_mean']):<16}")
    print(f"{'':25} {'':20} ({res2.std_errors['humidity_mean']:.4f}){'':<11} ({res3.std_errors['humidity_mean']:.4f})")
    print(f"{'Holiday':<25} {'—':<20} "
          f"{res2.params['holiday']:.4f}{get_stars(res2.pvalues['holiday']):<16} "
          f"{res3.params['holiday']:.4f}{get_stars(res3.pvalues['holiday']):<16}")
    print(f"{'Heatwave × Green':<25} {'—':<20} {'—':<20} {res3.params['heatwave_green']:.4f}{get_stars(res3.pvalues['heatwave_green']):<16}")
    print(f"{'':25} {'':20} {'':20} ({res3.std_errors['heatwave_green']:.4f})")
    print("-"*80)
    print(f"{'Observations':<25} {int(res1.nobs):<20,} {int(res2.nobs):<20,} {int(res3.nobs):<20,}")
    print(f"{'R²':<25} {res1.rsquared:<20.3f} {res2.rsquared_within:<20.3f} {res3.rsquared_within:<20.3f}")
    print(f"{'District FE':<25} {'No':<20} {'Yes':<20} {'Yes':<20}")
    print(f"{'Time FE':<25} {'No':<20} {'Yes':<20} {'Yes':<20}")
    print("="*80)
    print("Note: Standard errors in parentheses. * p<0.05, ** p<0.01, *** p<0.001")
    print("Models (2) and (3): Standard errors clustered at district level")

# ---------- Correlation + VIF ----------
def corr_and_vif(df, heatmap_path='correlation_matrix.png'):
    import seaborn as sns
    from statsmodels.stats.outliers_influence import variance_inflation_factor
    vars_to_check = ['heatwave_30_3d', 'precip', 'humidity_mean', 'holiday', 'green']
    corr_matrix = df[vars_to_check].corr()
    plt.figure(figsize=(8, 6))
    sns.heatmap(corr_matrix, annot=True, fmt='.3f', cmap='coolwarm',
                center=0, square=True, linewidths=1, cbar_kws={"shrink": 0.8})
    plt.title('Correlation Matrix: Key Variables', fontsize=14, fontweight='bold')
    plt.tight_layout()
    plt.savefig(heatmap_path, dpi=300, bbox_inches='tight')
    plt.show()
    vif_data = df[vars_to_check].dropna()
    vif_results = pd.DataFrame()
    vif_results["Variable"] = vars_to_check
    vif_results["VIF"] = [variance_inflation_factor(vif_data.values, i) for i in range(len(vars_to_check))]
    print("\n" + "="*50)
    print("Variance Inflation Factor (VIF) Test")
    print("="*50)
    print(vif_results)
    print("\nInterpretation:")
    print("VIF < 5: No multicollinearity concern")
    print("VIF 5-10: Moderate multicollinearity")
    print("VIF > 10: High multicollinearity (problematic)")
    return vif_results